# 문제 yaml - 관리가 불가능한 수준

apiVersion: v1
kind: Pod
metadata:
  name: web-frontend-1
spec:
  containers:
  - name: frontend
    image: nginx:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: web-backend-1
spec:
  containers:
  - name: backend
    image: node:latest
    ports:
    - containerPort: 3000
---
apiVersion: v1
kind: Pod
metadata:
  name: db-1
spec:
  containers:
  - name: database
    image: mysql:latest
    ports:
     - containerPort: 3306
